export const runtime="edge";
const fallback={headline:"Three loops need your attention before tomorrow.",done:["Updated the BYREDO installation visual","Sent production questions to Bam","Followed up with Red Bull"],open:["ASICS vertical project is newer than its latest render","ComplexCon estimate was edited but not sent"],owe:["Reply to Eddie’s lineup question"],waiting:["Bam — production budget response","Red Bull — sponsorship decision"],tomorrow:["Reply to Eddie before noon","Render and deliver ASICS vertical v12","Send the updated ComplexCon estimate"]};
const schema={type:"object",additionalProperties:false,properties:{headline:{type:"string"},done:{type:"array",items:{type:"string"}},open:{type:"array",items:{type:"string"}},owe:{type:"array",items:{type:"string"}},waiting:{type:"array",items:{type:"string"}},tomorrow:{type:"array",items:{type:"string"}}},required:["headline","done","open","owe","waiting","tomorrow"]};
export async function POST(req:Request){
 const {events}=await req.json();const key=process.env.OPENAI_API_KEY;
 if(!key)return Response.json(fallback);
 try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"authorization":"Bearer "+key,"content-type":"application/json"},body:JSON.stringify({model:"gpt-5.6",input:[{role:"system",content:"You are LOOP, an operating-system activity analyst. Infer work states from app, file, browser and email events. A file being edited is not proof of completion. Treat delivery, sending, export and external response as separate state transitions. Be concise, specific, and never invent names or events."},{role:"user",content:"Analyze today's activity and classify completed work, unfinished work, messages the user owes, responses they are waiting for, and the three best priorities for tomorrow. Events: "+JSON.stringify(events)}],text:{format:{type:"json_schema",name:"daily_loop_report",strict:true,schema}}})});
  if(!r.ok)return Response.json(fallback);const data=await r.json();const text=data.output_text||data.output?.[0]?.content?.[0]?.text;if(!text)return Response.json(fallback);return Response.json(JSON.parse(text));
 }catch{return Response.json(fallback)}
}
